### ISSUE TITLE
game review

### ISSUE THREAD

**Issue by muhkham** [WebAhead7/faster-typer#11]
nice game, I really liked it, and I will train my typing speed by playing it.
the legendary level is so cool and challenging. 
I would like to see other words using for different levels (like hard words for hard levels), or more variety, and not using the same word again sequentially.

one problem I found, you can start typing and playing the game without waiting the 3 sec counter ends. 

overall, impressive work, good job guys 👍

**Comment by muhammadawwad9** [comment]
Thx for your review muhammad,we fixed the issure using the function blur() 👍
