### ISSUE TITLE
Bug or feature ?

### ISSUE THREAD

**Issue by ghost** [WebAhead7/faster-typer#14]
Hey, I really enjoyed the design and the game itself. I can see a lot of words repetition in the game.
Maybe you need to implement function that will guarantee to return  new word each time you call it.
Very good game overall.

**Comment by alaabashiyi** [comment]
Thanks a lot Nizar ! we really appreciate it. well yea we had a very small array of words that's why some words are repeating. we added a new array with a lot of words, hope that'll do the job.
