### ISSUE TITLE
instead of random words, make a complete sentence 

### ISSUE THREAD

**Issue by Karyum** [WebAhead7/faster-typer#7]
there is a set amount of words and they repeat themselves, how about instead of the random words (type, designer, webahead7). make a complete sentence from start to finish, for easy mode it could be "I" "am" "big" "batata" 😆

**Comment by alaabashiyi** [comment]
this is the beautify of the game, one word each time not expecting what it's gonna be and it get really harder when you miss spell a word and losing time with funny music in the background! we're updating it soon. :D
